#Informa a pardir de qual imagem do site DockerHub sera gerada a nova imagem a ser criada
FROM mysql

#Introducao ENV que cria e atribui um valor para uma variavel
#(MSQ_ROOT_PASSWORD) dentro da imagem

ENV MYSQL_ROOT_PASSWORD teste