name: CI - teste calculadora Node.js Jest #nome do workflow (pipeline)

on: #eventos de gatilho que diparam o workflow(pipeline)
  push: #evento que push para a branchmain
    branches: #especificam as branches que disparam o evento push
      - main #evento de push para a branch main (corrigido o espaço)
  pull_request: # evento de pull request para as branches
    branches:
      - main
      - developer
      - fix
  workflow_dispatch: #permite disparar o workflow manualmente

jobs: # define os trabalhos (jobs) que serao executados no workflow
  build: #nome do trabalho (job)
    runs-on: ubuntu-latest #especifica o ambiente de execucao (runner) do trabalho
  
    strategy: # AGORA DENTRO DE BUILD: define a estragtegia de exeucao do trabalho (job)
      matrix: #define uma matriz de variaveis para executar o job em diferentes ambientes
        node-version: [18.x, 20.x] # Nota: atualizei as versões aqui para fazer sentido com o passo abaixo

    steps: # AGORA DENTRO DE BUILD: define os passos (steps) que serao executados no job
      - uses: actions/checkout@v4 #passo para fazer o checkout do codigo-fonte do respositorio

      - name: Use Node.js
        uses: actions/setup-node@v4 # acao para configurar o ambiente Node.js
        with: # AGORA DENTRO DE SETUP-NODE: especifica os parametros para a acao
          node-version: ${{ matrix.node-version }} # Usa a versão dinâmica da matrix acima

      - name: Install dependencies #passo para executar os testes do projeto
        run: npm ci # Comando correto para CI (instalação limpa baseada no package-lock.json)

      - name: Run Tests #passo para executar os testes do projeto
        run: npm test # Corrigido: o comando correto para rodar o jest usando o npm é 'npm test'